### ISSUE TITLE
Cannot view an address with balance is 0

### ISSUE THREAD

**Issue by codsay** [CasperDash/casperdash-mobile-wallet#25]
View mode with address: 02027b8db8cf675252c61e3de6932b3ac790ba39f1e99275aa2d3f05496767fe37cf
Test env: Android, S10+

**Comment by ThanhNguyen140797** [comment]
Please provide photos or video describe the bug.

**Comment by gaupoit** [comment]
hi @ThanhNguyen140797 , please try to use view mode with this address: 01fbb16c7c4d55a6e8fb7e96efa45b204d252de84c6c812046567c9a34588e25ba

And see the below video:


https://user-images.githubusercontent.com/4486806/156312775-878411ef-7e22-417b-ba47-e32d51d9007b.MP4


This errors means the account has never init due to no transactions before on-chain. We can ignore this error and allow user to login.
