### ISSUE TITLE
Submit for store review

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#34]
- Hide the no finished yet task: Staking, Market

**Comment by ThanhNguyen140797** [comment]
@gaupoit please check #42

**Comment by gaupoit** [comment]
hi @ThanhNguyen140797 , please help me to have a look this issue

```
Guideline 2.5.4 - Performance - Software Requirements



Your app declares support for bluetooth-peripheral in the UIBackgroundModes key in your Info.plist but does not provide Bluetooth Low Energy functionality. The Bluetooth Background modes are for apps that communicate to other devices using Bluetooth Low Energy and the Core Bluetooth framework.

Next Steps

To resolve this issue, please revise your app to add support for Bluetooth Low Energy communication through Core Bluetooth in your app or remove the bluetooth- values from the UIBackgroundModes key.

Resources

For more information on Core Bluetooth, please review the Core Bluetooth Framework Reference.
```

**Comment by ThanhNguyen140797** [comment]
Hi @gaupoit,
I think that issue occurs because using Background Modes - bluetooth. 
Remove it, then run the app on real devices, try to connect to ledger again. If the connection working fine, submit to review.
Sorry I can't check the ledger connection right now.

<img width="1169" alt="Screen Shot 2022-03-09 at 16 11 49" src="https://user-images.githubusercontent.com/34257375/157409993-b35db59a-6054-4583-959b-40eec7b9e55e.png">

**Comment by ThanhNguyen140797** [comment]
@gaupoit please check #54
